### ISSUE TITLE
Support for nvidia on Ubuntu Core 24

### ISSUE THREAD

**Issue by jocado** [canonical/docker-snap#204]
Hi.

I would like to add support for nvidia on Ubuntu Core 24 systems.  This means a couple of important changes:
- Switching to base `core24`
- Dropping support for nvidia on Ubuntu Core 22

Because of binary compatibility, it's not possible to support libraries from the host with different bases in a single snap.

I see two potential ways forward, but you may have other suggestions.
- Create a new track for `core22`, and publish a final release
- Create a new tracks for `core22` and `core24`, with git branches for each, and try and maintain support for both.

I presume that sooner or later it would be desirable to update the base, even without this feature.

I've submitted an [initial PR](https://github.com/canonical/docker-snap/pull/203), just to get the ball rolling and start discussion.  Happy to rebase as required once we find the best way forward and finish development.

I look forward to your comments, and any assistance you can provide.

Thank you!

**Comment by jocado** [comment]
Also just worth mentioning that the nvidia support in Ubuntu Core 24 is not quite ready for stable, but is expected to be in stable channel quite early next year.

**Comment by farshidtz** [comment]
Thanks @jocado for the issue, your proposals, and the PR. 

> Because of binary compatibility, it's not possible to support libraries from the host with different bases in a single snap.

Could you expand a bit on the binary compatibility requirement? Is this ABI boundary between `libnvidia-container`/`nvidia-container-toolkit` and the Nvidia userspace libraries (typically provided by nvidia-core22 or mesa-2404)? Or the boundary between those and the Nvidia kernel module?

**Comment by jocado** [comment]
Hmmm, now you are questioning it I'm not 100% binary compatibility is the issue I thought it was.

Compatibility between the kernel modules and userpsace libs should not be an issue we are concerned with here.  The versions there should be kept it sync at the point of release.

Compatibility between the nvidia-container-toolkit and the userspace libs is more what I was thinking, but just thinking about this again now, I'm not sure it's a problem.  The executables that run inside the snap just "parse" those libraries I believe on order to create the config which is used by the nvidia-runtime, and so I'm not sure they are actually relied on for any runtime.

It looks like the tests should cover this.  If it works, it works.  But, we would need to add support for different Ubuntu Core versions I think.

I can add back support for core22 [ currently dropped in the PR ], and have a look at the tests.

**Comment by farshidtz** [comment]
> It looks like the tests should cover this. If it works, it works. But, we would need to add support for different Ubuntu Core versions I think.
>
> I can add back support for core22 [ currently dropped in the PR ], and have a look at the tests.

The Nvidia tests run on Ubuntu 22.04 only, but we should be able to extend those for Ubuntu 24.04 as well as Ubuntu Core 22/24.

Smoke tests were recently changed (#207) to run also on Ubuntu 20.04 and 24.04 but they don't test the Nvidia runtime.

**Comment by jocado** [comment]
Just looking at the current nvidia tests code, it looks like we'll need to replace the `setup_core` with something like `setup_core22` and `setup_core24`.

Presumably the os choices used in the smoke test matrix were already existing OS images ?  Are there equivalents available for Ubuntu Core for use in Actions ?

**Comment by jocado** [comment]
Sorry, just answering my own question by reading the Actions docs [ I'm more familiar with Gitlab, and our custom setup ].

It looks like the runners used here are standard hosted runners, and nothing exists to run tests on UC.  I'm guessing that's why it's not setup that way already.

**Comment by jocado** [comment]
I've updated the PR, and added back the UC22 support, alongside the UC24 support.

It hasn't broken UC24 support, but I don't have a UC22 system with nvidia hardware to test on right now.

I'm keen to hear your thoughts on how we may be able to add nvidia tests on UC!  :+1:

**Comment by farshidtz** [comment]
Thanks for the updates. 
We will do some testing and comment on the PR.

> Just looking at the current nvidia tests code, it looks like we'll need to replace the `setup_core` with something like `setup_core22` and `setup_core24`.
> 
> Presumably the os choices used in the smoke test matrix were already existing OS images ? Are there equivalents available for Ubuntu Core for use in Actions ?

We [trigger](https://github.com/canonical/docker-snap/blob/71fd0c023c0aca1a4326f61c5886fa1f4db3997e/.github/workflows/nvidia-test.yml#L63-L67) the Nvidia tests via Github Actions but they run on devices with Nvidia GPUs in Canonical's test lab.
You can see [here](https://github.com/canonical/docker-snap/blob/71fd0c023c0aca1a4326f61c5886fa1f4db3997e/.github/workflows/testflinger/nvidia-job.yaml#L7) that the distro is currently set to `noble` which refers to Ubuntu Server 24.04. We can add Ubuntu Core to this; we have been doing that for manual testing in the past.

**Comment by jocado** [comment]
Hi @farshidtz 

Just FYI - looks like the UC24 pc-kernel snap with nvidia support is now in beta:
```
  24/beta:            6.8.0-58.60                 2025-04-09 (2414) 316MB -
```

```
squashfs-root.2414$ cat ./meta/snap.yaml
name: pc-kernel
version: 6.8.0-58.60
summary: Ubuntu generic kernel
description: The Ubuntu generic kernel package as a snap
type: kernel
architectures:
- amd64
confinement: strict
grade: stable
environment:
  LD_LIBRARY_PATH: ${SNAP_LIBRARY_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/lib
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
slots:
  kernel-gpu-2404:
    interface: content
    read:
    - $SNAP_COMMON/kernel-gpu-2404
links:
  contact:
  - https://answers.launchpad.net/canonical-kernel-snaps/+addquestion
  issues:
  - https://bugs.launchpad.net/canonical-kernel-snaps/+filebug?field.tags=pc-kernel
  source-code:
  - https://git.launchpad.net/~canonical-kernel-snaps/canonical-kernel-snaps/+git/kernel-snaps-u24.04
components:
  nvidia-550-erd-ko:
    summary: Nvidia 550-server kernel objects
    description: Nvidia 550-server driver kernel objects for the Ubuntu generic kernel
      snap
    type: kernel-modules
  nvidia-550-erd-user:
    summary: Nvidia 550-server userspace libraries
    description: Userspace libraries required by the Nvidia 550-server driver for
      the Ubuntu generic kernel snap
    type: standard
  nouveau-ko:
    summary: Nouveau kernel module
    description: The Nouveau kernel module for the Ubuntu generic kernel snap
    type: kernel-modules
```

If I get any further news regarding expected release timing later I'll update here.
